### ISSUE TITLE
Adam SLS us Adam SaLSa

### ISSUE THREAD

**Issue by katealenic** [TheMody/No-learning-rates-needed-Introducing-SALSA-Stable-Armijo-Line-Search-Adaptation#2]
It's interesting paper!

I found implementation for AdamSLS and is it Adam+SLS?
Or where I could find implementation for Adam SaLSa?

Thanks for help!

**Comment by TheMody** [comment]
The Adam + Salsa as described in the paper is from salsa.SaLSA import SaLSA. If you set the momentum parameter to (0,0,0.9) you will have SGD + Salsa.
Adam + SLS as described in the paper and previous publications is from salsa.adam_sls import AdamSLS.
