### ISSUE TITLE
Error appearing when no scheduler is set

### ISSUE THREAD

**Issue by Clod98** [TheMody/No-learning-rates-needed-Introducing-SALSA-Stable-Armijo-Line-Search-Adaptation#3]
Hello,

I'm trying to use Salsa in a comparison with other optimizers and I found the following issue:
when trying to run the optimizer without any scheduler the following error appears, 
```
File "/home/claudiu/miniconda3/envs/midas-py310/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 38, in __init__
    group.setdefault('initial_lr', group['lr'])
KeyError: 'lr'
```
This is due to the fact that no learning rate is specified in the optimizer. I found a simple work-around by adding
```
for group in optimizer.param_groups:
            group['lr'] = 0.0
```
after the initialization of Salsa optimizer.
hope this helps,

Claudiu

**Comment by TheMody** [comment]
I don't understand what you did here? Can you please specifiy more of your code. The SaLSa optimizer does not need a scheduler and also does not need a learning rate. That is the point of the optimizer. Your "fix" sets a learning rate, but this learning rate does not do anything and does not get used. If you want to retrieve the learning rate determined automatically by the SaLSa optimizer you can do so with: lr = optimizer.state["lr"]

**Comment by Clod98** [comment]
It was an issue in my code, I solved it.
Thank you anyway :+1:
